config/routes.rb
Rails.application.routes.draw do
  resources :tweets

  resources :tweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 140} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :find_tweet, only:[:edit,:update,:destroy]

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create 
    @tweet = Tweet.new(get_tweet_params)
    if params[:'back']
      render:new
    elsif @tweet.save 
      redirect_to tweets_path, notice:"作成しました"
    else
      render:new
    end
  end

  def edit
  end

  def update
    if @tweet.update(get_tweet_params)
      redirect_to tweets_path, notice:"編集しました"
    else
      render:edit
    end
  end

  def destroy
   if @tweet.destroy
    redirect_to tweets_path,notice:"削除しました。"
  else
    render:edit
   end
  end

  def confirm
    @tweet = Tweet.new(get_tweet_params)
    render :new if @tweet.invalid?
  end

  private
  def find_tweet
    @tweet = Tweet.find(params[:id])
  end

  def get_tweet_params
    params.require(:tweet).permit(:content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def chooes_new_or_edit
    if action_name == 'new' 
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mutter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
  <body>
    <header>
        <a>mutter<a>
        <%= link_to '投稿',new_tweet_path %>
        <%= link_to '一覧',tweets_path %>
    </header>

    <%= yield %>

    <footer class="footer">
      <p>運営会社DIVE INTO CODE株式会社</p>
      <p>© 0001-9999 Copyright DIVE INTO CODE Corp.</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="input_form">
  <%= form_with(model: @tweet, local: true ,url: chooes_new_or_edit ) do |form| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>   
        <ul>
          <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ulr>
      </div>
    <% end %>
    <div>
      <%= form.text_field :content ,value: @tweet.content %>
    </div>
    <%= form.submit %>
  <% end %>
  <%= link_to "一覧画面にもどる", tweets_path %>
</div>

app/views/tweets/confirm.html.erb
<h3>以下の内容で、Tweetしますか？</h3>
<%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @tweet.content %></p>
  <%= form.submit "Tweetする" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tweets/edit.html.erb
<h2>Tweetを編集する</h2>
<%= render 'form' %>

app/views/tweets/index.html.erb
<h3>Tweets</h3>
<table>
<tr>
  <%= notice %>
</tr>
  <tr>
    <th>Tweets一覧</th>
  </tr>
  <% @tweets.each do |tweet| %>
    <tr>
      <td>
        <%= tweet.content %>
      </td>
      <td>
        <%= link_to "編集する", edit_tweet_path(tweet.id) %>
        <%= link_to "削除する", tweet_path(tweet.id),method: :delete, data:{   confirm:"本当に編集しても良いですか？"}  %>
      </td>  
    </tr>
  <% end %>
</table>

app/views/tweets/new.html.erb
<h2>Tweetを登録する</h2>
<%= render 'form' %>